### PR TITLE
Wrap components in IIFEs

### PR DESCRIPTION
**Pull request by cadebward**

### CODE REVIEW

**Comment by cadebward** [comment]
I got two commits in here before I figured out how to do one at a time. My bad..

**Comment by cadebward** [comment]
Yeah i wasn't 100% with that either. So let's just bag that. What do you think about using IIFEs?

**Comment by RussMax783** [comment]
sorry I didn't see the new description. still getting used to this.  I think IIFEs should be done across the board!

**Comment by cadebward** [comment]
Okay this was a messy pull request, but I think I've cleaned it up pretty well now. This request only includes `IIFE`s now.

**Pull request merged**
